addresses:
  - "CTzsBJXGzySbPGguaoHxYj6K3mfmSNL1YQppxacLtWY2"
  - "BSfQsF9RQH2h51FnHASpFin6XYQeXFK4rak9vtQxsA85"
  - "H5qgsZ83D6kyMhq9dvLzLxm27p5yPywJWESyFMr69VwH"
  - "bKnQuoFJkhJvaTfEtvv1bQxJwnU1Qoor3C8nZ2x9VZR"
  - "JdZKDMEfDajthXWk9fzVhf3Mm4QEctNZtuTsDjtdz2t"
  - "7CuEURhrAAJfaUAzUhAhiCheLWf7Ep1y2oU7Pkd4VmmQ"
